# Generated by Django 3.2 on 2021-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '隐藏'), (3, '隐藏'), (4, '隐藏')], default=1, verbose_name='展示类型'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '显示'), (0, '隐藏')], default=1, verbose_name='状态'),
        ),
    ]
